name: "🧩 알고리즘 문제 풀이"
description: "문제 풀이 기록 자동 생성"

body:
  - type: input
    attributes:
      label: 📌 문제 제목
      description: "커밋 메시지에서 자동 입력됩니다."
      placeholder: "[Silver IV] ATM"
  - type: input
    attributes:
      label: 🔗 Commit Link
      description: "해당 문제 풀이 커밋 링크"
      placeholder: "https://github.com/Masiljangajji/Algorithm/commit/<SHA>"
  - type: textarea
    attributes:
      label: ✨ 배운 점 / 회고
      description: "문제를 풀면서 배운 점을 자유롭게 기록하세요."
