name: "오늘도 생각했나요"
description: "규칙 규칙 규칙."
body:
  - type: textarea
    attributes:
      label: ✅ 작업할 내용
      description: 할 일을 체크박스 형태로 작성하세요.
      value: |
        - [ ] 1일 1커밋
        - [ ] 1일 1산책
        - [ ] 1주 1포스팅
        - [ ] 1달 1독서
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🙋🏻 참고 자료
      description: 참고할 자료가 있다면 입력하세요.